[package]
name = "tiger_syntax"
version = "0.1.0"
authors = ["gustavderdrache <gustavderdrache@gmail.com>"]
edition = "2018"

[dependencies]
enum-kinds = "0.4.1"
enum-map = "0.5.0"
env_logger = "0.6.1"
indexmap = "1.0.2"
lazy_static = "1.3.0"
log = "0.4.6"
